-- VoipVoice Talent Assessment - Supabase setup
-- Esegui questo file UNA VOLTA nel SQL Editor di Supabase.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
revoke create on schema public from public;

create table if not exists public.hr_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.test_versions (
  id bigint generated by default as identity primary key,
  label text not null unique,
  data jsonb not null,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  published_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.test_draft (
  id integer primary key default 1 check (id = 1),
  data jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  candidate_name text not null,
  position text,
  version_id bigint not null references public.test_versions(id),
  status text not null default 'invited' check (status in ('invited','started','completed')),
  answers jsonb not null default '{}'::jsonb,
  result jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  completed_at timestamptz,
  created_by uuid references auth.users(id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id),
  event text not null
);

alter table public.hr_users enable row level security;
alter table public.test_versions enable row level security;
alter table public.test_draft enable row level security;
alter table public.invitations enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.hr_users, public.test_versions, public.test_draft, public.invitations, public.audit_logs from anon, authenticated;
revoke all on sequence public.test_versions_id_seq, public.invitations_id_seq, public.audit_logs_id_seq from anon, authenticated;

create or replace function private.token_hash(p_token text)
returns text
language sql
immutable
security definer
set search_path = public, extensions, pg_temp
as $$
  select encode(extensions.digest(coalesce(p_token,''), 'sha256'), 'hex');
$$;

create or replace function private.require_hr()
returns uuid
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null or not exists(select 1 from public.hr_users h where h.user_id=v_user) then
    raise exception 'HR_AUTH_REQUIRED';
  end if;
  return v_user;
end;
$$;

create or replace function private.validate_test_data(p_data jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  q jsonb;
  a jsonb;
  pri text;
  sec text;
  qid text;
  answer_count integer;
begin
  if p_data is null or jsonb_typeof(p_data) <> 'object' then raise exception 'INVALID_TEST_CONFIG'; end if;
  if jsonb_typeof(p_data->'questions') is distinct from 'array' or jsonb_array_length(p_data->'questions') < 1 then raise exception 'INVALID_TEST_CONFIG'; end if;
  if jsonb_typeof(p_data->'competencies') is distinct from 'array' or jsonb_array_length(p_data->'competencies') < 1 then raise exception 'INVALID_TEST_CONFIG'; end if;
  if jsonb_typeof(p_data->'ranges') is distinct from 'array' or jsonb_array_length(p_data->'ranges') < 1 then raise exception 'INVALID_TEST_CONFIG'; end if;

  if exists(
    select 1 from (
      select value->>'id' as id, count(*) c
      from jsonb_array_elements(p_data->'questions')
      group by value->>'id'
      having count(*) > 1
    ) s
  ) then raise exception 'INVALID_TEST_CONFIG'; end if;

  for q in select value from jsonb_array_elements(p_data->'questions') loop
    qid := q->>'id';
    if qid is null or nullif(trim(q->>'text'),'') is null then raise exception 'INVALID_TEST_CONFIG'; end if;
    if coalesce(q->>'type','') not in ('scale','scenario') then raise exception 'INVALID_TEST_CONFIG'; end if;
    if jsonb_typeof(q->'answers') is distinct from 'array' or jsonb_array_length(q->'answers') < 2 then raise exception 'INVALID_TEST_CONFIG'; end if;
    pri := q->'scoring'->>'primary'; sec := nullif(q->'scoring'->>'secondary','');
    if pri is null or not exists(select 1 from jsonb_array_elements(p_data->'competencies') c where c->>'name'=pri) then raise exception 'INVALID_TEST_CONFIG'; end if;
    if sec is not null and not exists(select 1 from jsonb_array_elements(p_data->'competencies') c where c->>'name'=sec) then raise exception 'INVALID_TEST_CONFIG'; end if;

    select count(*) into answer_count from (
      select value->>'key' k from jsonb_array_elements(q->'answers') group by value->>'key'
    ) x;
    if answer_count <> jsonb_array_length(q->'answers') then raise exception 'INVALID_TEST_CONFIG'; end if;

    for a in select value from jsonb_array_elements(q->'answers') loop
      if nullif(a->>'key','') is null or nullif(a->>'text','') is null or jsonb_typeof(a->'points') is distinct from 'number' then
        raise exception 'INVALID_TEST_CONFIG';
      end if;
    end loop;
  end loop;

  if coalesce((p_data->'weights'->>'primary')::numeric,1) < 0 or coalesce((p_data->'weights'->>'secondary')::numeric,1) < 0 then
    raise exception 'INVALID_TEST_CONFIG';
  end if;
end;
$$;

create or replace function private.validate_answers(p_data jsonb, p_answers jsonb, p_require_all boolean)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  q jsonb;
  k text;
  answer_key text;
  total_keys integer;
begin
  if p_answers is null or jsonb_typeof(p_answers) <> 'object' then raise exception 'INVALID_ANSWER'; end if;
  select count(*) into total_keys from jsonb_object_keys(p_answers);
  if total_keys > 100 then raise exception 'INVALID_ANSWER'; end if;

  for k in select key from jsonb_each(p_answers) loop
    if not exists(select 1 from jsonb_array_elements(p_data->'questions') q2 where q2->>'id'=k) then
      raise exception 'INVALID_ANSWER';
    end if;
  end loop;

  for q in select value from jsonb_array_elements(p_data->'questions') loop
    k := q->>'id';
    if not (p_answers ? k) then
      if p_require_all then raise exception 'MISSING_ANSWER'; end if;
      continue;
    end if;
    answer_key := p_answers->>k;
    if not exists(select 1 from jsonb_array_elements(q->'answers') a where a->>'key'=answer_key) then
      raise exception 'INVALID_ANSWER';
    end if;
  end loop;
end;
$$;

create or replace function private.calculate_result(p_data jsonb, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  q jsonb; a jsonb; comp jsonb;
  answer_key text; pri text; sec text; cname text;
  points numeric; selected_points numeric; lo numeric; hi numeric; score numeric;
  primary_weight numeric := coalesce((p_data->'weights'->>'primary')::numeric,1);
  secondary_weight numeric := coalesce((p_data->'weights'->>'secondary')::numeric,1);
  sums jsonb := '{}'::jsonb; weights jsonb := '{}'::jsonb; scores jsonb := '{}'::jsonb;
  scenario_sum numeric := 0; scenario_count integer := 0;
begin
  perform private.validate_answers(p_data,p_answers,true);

  for comp in select value from jsonb_array_elements(p_data->'competencies') loop
    cname := comp->>'name';
    sums := jsonb_set(sums,array[cname],to_jsonb(0::numeric),true);
    weights := jsonb_set(weights,array[cname],to_jsonb(0::numeric),true);
  end loop;

  for q in select value from jsonb_array_elements(p_data->'questions') loop
    answer_key := p_answers->>(q->>'id');
    selected_points := null; lo := null; hi := null;
    for a in select value from jsonb_array_elements(q->'answers') loop
      points := (a->>'points')::numeric;
      if lo is null or points < lo then lo := points; end if;
      if hi is null or points > hi then hi := points; end if;
      if a->>'key'=answer_key then selected_points := points; end if;
    end loop;
    if selected_points is null then raise exception 'INVALID_ANSWER'; end if;
    if coalesce((q->'scoring'->>'inverse')::boolean,false) and q->>'type'='scale' then selected_points := lo + hi - selected_points; end if;
    score := case when hi=lo then 0 else ((selected_points-lo)/(hi-lo))*100 end;

    if q->>'type'='scenario' then scenario_sum:=scenario_sum+score; scenario_count:=scenario_count+1; end if;
    pri := q->'scoring'->>'primary'; sec := nullif(q->'scoring'->>'secondary','');

    if pri is not null and sums ? pri and primary_weight>0 then
      sums := jsonb_set(sums,array[pri],to_jsonb(((sums->>pri)::numeric)+(score*primary_weight)),true);
      weights := jsonb_set(weights,array[pri],to_jsonb(((weights->>pri)::numeric)+primary_weight),true);
    end if;
    if sec is not null and sums ? sec and secondary_weight>0 then
      sums := jsonb_set(sums,array[sec],to_jsonb(((sums->>sec)::numeric)+(score*secondary_weight)),true);
      weights := jsonb_set(weights,array[sec],to_jsonb(((weights->>sec)::numeric)+secondary_weight),true);
    end if;
  end loop;

  for comp in select value from jsonb_array_elements(p_data->'competencies') loop
    cname := comp->>'name';
    scores := jsonb_set(scores,array[cname],to_jsonb(case when (weights->>cname)::numeric=0 then 0 else (sums->>cname)::numeric/(weights->>cname)::numeric end),true);
  end loop;

  return jsonb_build_object(
    'scores',scores,
    'scenarioScore',case when scenario_count=0 then 0 else scenario_sum/scenario_count end,
    'createdAt',now()
  );
end;
$$;

create or replace function public.candidate_get_test(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  inv public.invitations%rowtype; v public.test_versions%rowtype;
  q jsonb; a jsonb; safe_q jsonb; safe_a jsonb; questions jsonb := '[]'::jsonb;
begin
  select * into inv from public.invitations where token_hash=private.token_hash(p_token);
  if not found then raise exception 'LINK_NOT_FOUND'; end if;
  if inv.status<>'completed' and inv.expires_at<now() then raise exception 'LINK_EXPIRED'; end if;
  select * into v from public.test_versions where id=inv.version_id;

  if inv.status<>'completed' then
    for q in select value from jsonb_array_elements(v.data->'questions') loop
      safe_a := '[]'::jsonb;
      for a in select value from jsonb_array_elements(q->'answers') loop
        safe_a := safe_a || jsonb_build_array(jsonb_build_object('key',a->>'key','text',a->>'text'));
      end loop;
      safe_q := jsonb_build_object('id',(q->>'id')::int,'text',q->>'text','type',q->>'type','answers',safe_a);
      questions := questions || jsonb_build_array(safe_q);
    end loop;
  end if;

  return jsonb_build_object(
    'name',inv.candidate_name,'position',inv.position,'version',v.label,'status',inv.status,
    'expiresAt',inv.expires_at,'answers',case when inv.status='completed' then '{}'::jsonb else inv.answers end,
    'questions',questions
  );
end;
$$;

create or replace function public.candidate_start(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare inv public.invitations%rowtype;
begin
  select * into inv from public.invitations where token_hash=private.token_hash(p_token) for update;
  if not found then raise exception 'LINK_NOT_FOUND'; end if;
  if inv.status='completed' then raise exception 'TEST_COMPLETED'; end if;
  if inv.expires_at<now() then raise exception 'LINK_EXPIRED'; end if;
  update public.invitations set status='started' where id=inv.id and status='invited';
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.candidate_save(p_token text, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare inv public.invitations%rowtype; v public.test_versions%rowtype;
begin
  select * into inv from public.invitations where token_hash=private.token_hash(p_token) for update;
  if not found then raise exception 'LINK_NOT_FOUND'; end if;
  if inv.status='completed' then raise exception 'TEST_COMPLETED'; end if;
  if inv.expires_at<now() then raise exception 'LINK_EXPIRED'; end if;
  select * into v from public.test_versions where id=inv.version_id;
  perform private.validate_answers(v.data,p_answers,false);
  update public.invitations set answers=p_answers,status='started' where id=inv.id;
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.candidate_submit(p_token text, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare inv public.invitations%rowtype; v public.test_versions%rowtype; r jsonb;
begin
  select * into inv from public.invitations where token_hash=private.token_hash(p_token) for update;
  if not found then raise exception 'LINK_NOT_FOUND'; end if;
  if inv.status='completed' then raise exception 'TEST_COMPLETED'; end if;
  if inv.expires_at<now() then raise exception 'LINK_EXPIRED'; end if;
  select * into v from public.test_versions where id=inv.version_id;
  r := private.calculate_result(v.data,p_answers);
  update public.invitations set answers=p_answers,result=r,status='completed',completed_at=now() where id=inv.id;
  insert into public.audit_logs(event) values ('Test completato — candidato #'||inv.id||' — versione '||v.label);
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.hr_bootstrap()
returns jsonb
language plpgsql
security definer
set search_path = public, private, auth, pg_temp
as $$
declare u uuid; v public.test_versions%rowtype; email_value text;
begin
  u:=private.require_hr();
  select * into v from public.test_versions where is_current order by id desc limit 1;
  select email into email_value from auth.users where id=u;
  return jsonb_build_object('currentVersion',v.label,'email',email_value);
end;
$$;

create or replace function public.hr_list_candidates()
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare items jsonb;
begin
  perform private.require_hr();
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',i.id,'name',i.candidate_name,'position',i.position,'version',v.label,
    'status',case when i.status<>'completed' and i.expires_at<now() then 'expired' else i.status end,
    'createdAt',i.created_at,'expiresAt',i.expires_at,'completedAt',i.completed_at
  ) order by i.created_at desc),'[]'::jsonb)
  into items
  from public.invitations i join public.test_versions v on v.id=i.version_id;
  return jsonb_build_object('items',items);
end;
$$;

create or replace function public.hr_create_invitation(p_name text, p_position text default null, p_expiry_days integer default 14)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare u uuid; v public.test_versions%rowtype; tok text; new_id bigint; exp timestamptz;
begin
  u:=private.require_hr();
  if nullif(trim(p_name),'') is null then raise exception 'Nome candidato obbligatorio'; end if;
  if p_expiry_days<1 or p_expiry_days>90 then raise exception 'Scadenza non valida'; end if;
  select * into v from public.test_versions where is_current order by id desc limit 1;
  tok:=encode(extensions.gen_random_bytes(24),'hex'); exp:=now()+make_interval(days=>p_expiry_days);
  insert into public.invitations(token_hash,candidate_name,position,version_id,expires_at,created_by)
  values(private.token_hash(tok),trim(p_name),nullif(trim(coalesce(p_position,'')),''),v.id,exp,u) returning id into new_id;
  insert into public.audit_logs(user_id,event) values(u,'Creato invito #'||new_id||' — versione '||v.label);
  return jsonb_build_object('id',new_id,'token',tok,'version',v.label,'expiresAt',exp);
end;
$$;

create or replace function public.hr_rotate_invitation_token(p_invitation_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare u uuid; inv public.invitations%rowtype; tok text;
begin
  u:=private.require_hr();
  select * into inv from public.invitations where id=p_invitation_id for update;
  if not found then raise exception 'INVITATION_NOT_FOUND'; end if;
  if inv.status='completed' then raise exception 'TEST_COMPLETED'; end if;
  tok:=encode(extensions.gen_random_bytes(24),'hex');
  update public.invitations set token_hash=private.token_hash(tok) where id=inv.id;
  insert into public.audit_logs(user_id,event) values(u,'Rigenerato link invito #'||inv.id);
  return jsonb_build_object('token',tok,'expiresAt',inv.expires_at);
end;
$$;

create or replace function public.hr_get_result(p_invitation_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare inv public.invitations%rowtype; v public.test_versions%rowtype;
begin
  perform private.require_hr();
  select * into inv from public.invitations where id=p_invitation_id;
  if not found then raise exception 'INVITATION_NOT_FOUND'; end if;
  if inv.status<>'completed' or inv.result is null then raise exception 'RESULT_NOT_AVAILABLE'; end if;
  select * into v from public.test_versions where id=inv.version_id;
  return jsonb_build_object(
    'candidate',jsonb_build_object('id',inv.id,'name',inv.candidate_name,'position',inv.position,'version',v.label,'completedAt',inv.completed_at),
    'result',inv.result,
    'config',v.data
  );
end;
$$;

create or replace function public.hr_get_settings()
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare v public.test_versions%rowtype; d public.test_draft%rowtype;
begin
  perform private.require_hr();
  select * into v from public.test_versions where is_current order by id desc limit 1;
  select * into d from public.test_draft where id=1;
  return jsonb_build_object('currentVersion',v.label,'hasDraft',d.id is not null,'data',coalesce(d.data,v.data));
end;
$$;

create or replace function public.hr_save_draft(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare u uuid;
begin
  u:=private.require_hr(); perform private.validate_test_data(p_data);
  insert into public.test_draft(id,data,updated_at,updated_by) values(1,p_data,now(),u)
  on conflict(id) do update set data=excluded.data,updated_at=excluded.updated_at,updated_by=excluded.updated_by;
  insert into public.audit_logs(user_id,event) values(u,'Salvata bozza configurazione test');
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.hr_discard_draft()
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare u uuid;
begin
  u:=private.require_hr(); delete from public.test_draft where id=1;
  insert into public.audit_logs(user_id,event) values(u,'Bozza configurazione eliminata');
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.hr_publish_settings(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare u uuid; v public.test_versions%rowtype; major_part text; minor_part integer; new_label text;
begin
  u:=private.require_hr(); perform private.validate_test_data(p_data);
  select * into v from public.test_versions where is_current order by id desc limit 1 for update;
  major_part:=coalesce(nullif(split_part(v.label,'.',1),''),'1');
  minor_part:=coalesce(nullif(split_part(v.label,'.',2),'')::integer,0)+1;
  new_label:=major_part||'.'||minor_part;
  update public.test_versions set is_current=false where is_current;
  insert into public.test_versions(label,data,is_current,published_at,created_by) values(new_label,p_data,true,now(),u);
  delete from public.test_draft where id=1;
  insert into public.audit_logs(user_id,event) values(u,'Pubblicata versione test '||new_label);
  return jsonb_build_object('version',new_label);
end;
$$;

create or replace function public.hr_audit()
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare versions jsonb; logs jsonb;
begin
  perform private.require_hr();
  select coalesce(jsonb_agg(jsonb_build_object(
    'label',v.label,'createdAt',v.published_at,'isCurrent',v.is_current,
    'invitations',(select count(*) from public.invitations i where i.version_id=v.id)
  ) order by v.id desc),'[]'::jsonb) into versions from public.test_versions v;
  select coalesce(jsonb_agg(jsonb_build_object('event',a.event,'createdAt',a.created_at) order by a.id desc),'[]'::jsonb)
  into logs from (select * from public.audit_logs order by id desc limit 100) a;
  return jsonb_build_object('versions',versions,'audit',logs);
end;
$$;

-- Blocca l'esecuzione implicita delle funzioni: concediamo solo ciò che serve.
revoke all on function public.candidate_get_test(text) from public;
revoke all on function public.candidate_start(text) from public;
revoke all on function public.candidate_save(text,jsonb) from public;
revoke all on function public.candidate_submit(text,jsonb) from public;
grant execute on function public.candidate_get_test(text), public.candidate_start(text), public.candidate_save(text,jsonb), public.candidate_submit(text,jsonb) to anon, authenticated;

revoke all on function public.hr_bootstrap() from public;
revoke all on function public.hr_list_candidates() from public;
revoke all on function public.hr_create_invitation(text,text,integer) from public;
revoke all on function public.hr_rotate_invitation_token(bigint) from public;
revoke all on function public.hr_get_result(bigint) from public;
revoke all on function public.hr_get_settings() from public;
revoke all on function public.hr_save_draft(jsonb) from public;
revoke all on function public.hr_discard_draft() from public;
revoke all on function public.hr_publish_settings(jsonb) from public;
revoke all on function public.hr_audit() from public;
grant execute on function public.hr_bootstrap(), public.hr_list_candidates(), public.hr_create_invitation(text,text,integer), public.hr_rotate_invitation_token(bigint), public.hr_get_result(bigint), public.hr_get_settings(), public.hr_save_draft(jsonb), public.hr_discard_draft(), public.hr_publish_settings(jsonb), public.hr_audit() to authenticated;

-- Seed iniziale del test (40 domande reali + scoring derivato dall'Excel).
do $bootstrap$
begin
  if not exists(select 1 from public.test_versions) then
    insert into public.test_versions(label,data,is_current,published_at)
    values('1.0',$vvseed${
  "questions": [
    {
      "id": 1,
      "text": "Quando mi viene affidato un compito, mi assicuro di portarlo a termine anche se nessuno controlla direttamente il mio lavoro.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Accountability e affidabilità",
        "secondary": null
      }
    },
    {
      "id": 2,
      "text": "Quando incontro un problema nuovo, cerco prima di comprenderne le cause invece di provare immediatamente una soluzione.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": null
      }
    },
    {
      "id": 3,
      "text": "Mi trovo a mio agio nel confrontarmi con persone che hanno opinioni diverse dalle mie.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 4,
      "text": "Un cambiamento improvviso nei programmi tende a mettermi molto in difficoltà.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": true,
        "primary": "Adattabilità",
        "secondary": null
      }
    },
    {
      "id": 5,
      "text": "Quando ho un obiettivo chiaro, organizzo autonomamente le attività necessarie per raggiungerlo.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Autonomia e iniziativa",
        "secondary": "Orientamento al risultato"
      }
    },
    {
      "id": 6,
      "text": "Se commetto un errore, preferisco comunicarlo rapidamente e cercare una soluzione.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Accountability e affidabilità",
        "secondary": null
      }
    },
    {
      "id": 7,
      "text": "Prima di prendere una decisione importante cerco di raccogliere le informazioni realmente necessarie.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": null
      }
    },
    {
      "id": 8,
      "text": "Quando lavoro in gruppo, cerco di capire anche le esigenze degli altri componenti del team.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 9,
      "text": "Preferisco lavorare sempre nello stesso modo, anche quando esistono alternative potenzialmente migliori.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": true,
        "primary": "Adattabilità",
        "secondary": null
      }
    },
    {
      "id": 10,
      "text": "Se un'attività si rivela più difficile del previsto, tendo comunque a cercare un modo per completarla.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Orientamento al risultato",
        "secondary": "Autonomia e iniziativa"
      }
    },
    {
      "id": 11,
      "text": "Rispetto scadenze e impegni anche quando contemporaneamente ho molte attività da gestire.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Accountability e affidabilità",
        "secondary": null
      }
    },
    {
      "id": 12,
      "text": "Davanti a informazioni contraddittorie, cerco di distinguere i fatti dalle interpretazioni.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": null
      }
    },
    {
      "id": 13,
      "text": "Quando non sono d'accordo con un collega riesco generalmente a spiegare la mia posizione senza creare inutili tensioni.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 14,
      "text": "Riesco ad adattarmi abbastanza rapidamente a strumenti, procedure o modalità di lavoro nuove.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Adattabilità",
        "secondary": null
      }
    },
    {
      "id": 15,
      "text": "Mi capita di perdere interesse per un'attività quando i risultati non arrivano velocemente.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": true,
        "primary": "Orientamento al risultato",
        "secondary": null
      }
    },
    {
      "id": 16,
      "text": "Se mi accorgo di non riuscire a rispettare una scadenza, avviso le persone coinvolte prima che diventi un problema.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Accountability e affidabilità",
        "secondary": null
      }
    },
    {
      "id": 17,
      "text": "Quando una prima soluzione non funziona, provo a osservare il problema da un punto di vista diverso.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": null
      }
    },
    {
      "id": 18,
      "text": "Mi interessa condividere informazioni che possono aiutare i colleghi a lavorare meglio.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 19,
      "text": "Quando cambiano le priorità, riesco a riorganizzare il mio lavoro senza perdere di vista gli obiettivi principali.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Adattabilità",
        "secondary": null
      }
    },
    {
      "id": 20,
      "text": "Mi piace capire in che modo il mio lavoro contribuisce a un risultato più ampio.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Orientamento al risultato",
        "secondary": null
      }
    },
    {
      "id": 21,
      "text": "Se ricevo un'indicazione poco chiara, preferisco chiedere un chiarimento piuttosto che procedere sulla base di supposizioni.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Accountability e affidabilità",
        "secondary": "Autonomia e iniziativa"
      }
    },
    {
      "id": 22,
      "text": "Di fronte a un problema complesso tendo a dividerlo in parti più semplici da affrontare.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": "Autonomia e iniziativa"
      }
    },
    {
      "id": 23,
      "text": "Se un collega è in difficoltà e posso aiutarlo senza compromettere le mie priorità, cerco di farlo.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 24,
      "text": "Lavorare in situazioni in cui non tutte le informazioni sono disponibili mi blocca facilmente.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": true,
        "primary": "Adattabilità",
        "secondary": null
      }
    },
    {
      "id": 25,
      "text": "Quando raggiungo un risultato, cerco di capire anche cosa avrei potuto fare meglio.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Orientamento al risultato",
        "secondary": null
      }
    },
    {
      "id": 26,
      "text": "Quando qualcosa va storto, la mia prima reazione è cercare di capire di chi sia la responsabilità.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": true,
        "primary": "Accountability e affidabilità",
        "secondary": null
      }
    },
    {
      "id": 27,
      "text": "Riesco a modificare la mia opinione quando emergono elementi concreti che dimostrano che un'altra soluzione è migliore.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": "Adattabilità"
      }
    },
    {
      "id": 28,
      "text": "Durante una discussione tendo ad ascoltare completamente l'altra persona prima di formulare la mia risposta.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 29,
      "text": "Preferisco aspettare istruzioni precise prima di iniziare qualsiasi attività.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": true,
        "primary": "Autonomia e iniziativa",
        "secondary": null
      }
    },
    {
      "id": 30,
      "text": "Quando devo scegliere tra più attività, considero priorità, scadenze e impatto sul risultato.",
      "type": "scale",
      "answers": [
        {
          "key": "1",
          "text": "Per niente d’accordo",
          "points": 1
        },
        {
          "key": "2",
          "text": "Poco",
          "points": 2
        },
        {
          "key": "3",
          "text": "Né/Né",
          "points": 3
        },
        {
          "key": "4",
          "text": "Abbastanza",
          "points": 4
        },
        {
          "key": "5",
          "text": "Del tutto d’accordo",
          "points": 5
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Orientamento al risultato",
        "secondary": "Autonomia e iniziativa"
      }
    },
    {
      "id": 31,
      "text": "Hai tre attività da completare nella stessa giornata e ti accorgi che probabilmente non riuscirai a rispettare tutte le scadenze.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Chiedo al responsabile di indicarmi immediatamente quale attività devo svolgere per prima.",
          "points": 3
        },
        {
          "key": "B",
          "text": "Lavoro più velocemente possibile e verifico a fine giornata cosa sono riuscito a terminare.",
          "points": 1
        },
        {
          "key": "C",
          "text": "Valuto urgenza e impatto, definisco le priorità e segnalo tempestivamente eventuali criticità.",
          "points": 4
        },
        {
          "key": "D",
          "text": "Le completo nell'ordine in cui mi sono state assegnate.",
          "points": 2
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Orientamento al risultato",
        "secondary": "Autonomia e iniziativa"
      }
    },
    {
      "id": 32,
      "text": "Ti accorgi di aver commesso un errore che potrebbe avere conseguenze sul lavoro di un collega.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Informo rapidamente le persone coinvolte, propongo una soluzione e verifico come evitare che accada nuovamente.",
          "points": 4
        },
        {
          "key": "B",
          "text": "Spiego innanzitutto quali circostanze mi hanno portato a commettere l'errore.",
          "points": 1
        },
        {
          "key": "C",
          "text": "Aspetto di capire se l'errore avrà effettivamente conseguenze.",
          "points": 1
        },
        {
          "key": "D",
          "text": "Correggo l'errore autonomamente e non ne parlo se riesco a risolverlo.",
          "points": 2
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Accountability e affidabilità",
        "secondary": null
      }
    },
    {
      "id": 33,
      "text": "Durante una riunione un collega propone una soluzione molto diversa dalla tua.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Difendo la mia proposta perché l'ho già analizzata approfonditamente.",
          "points": 1
        },
        {
          "key": "B",
          "text": "Chiedo al responsabile quale delle due soluzioni preferisce.",
          "points": 2
        },
        {
          "key": "C",
          "text": "Evito il confronto e accetto la sua proposta.",
          "points": 2
        },
        {
          "key": "D",
          "text": "Cerco di capire il suo ragionamento e confronto le due soluzioni sulla base di informazioni e obiettivi.",
          "points": 4
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": null
      }
    },
    {
      "id": 34,
      "text": "Ti viene assegnata un'attività che non hai mai svolto.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Procedo autonomamente senza coinvolgere nessuno.",
          "points": 3
        },
        {
          "key": "B",
          "text": "Cerco di capire l'obiettivo, raccolgo le informazioni necessarie, imposto il lavoro e chiedo supporto sui punti che non riesco a risolvere.",
          "points": 4
        },
        {
          "key": "C",
          "text": "Chiedo che l'attività venga affidata a qualcuno con maggiore esperienza.",
          "points": 1
        },
        {
          "key": "D",
          "text": "Aspetto istruzioni dettagliate prima di iniziare.",
          "points": 2
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Autonomia e iniziativa",
        "secondary": "Adattabilità"
      }
    },
    {
      "id": 35,
      "text": "Una priorità sulla quale stai lavorando da diversi giorni viene improvvisamente ridimensionata a favore di una nuova urgenza.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Continuo prima a terminare il lavoro già iniziato.",
          "points": 1
        },
        {
          "key": "B",
          "text": "Aspetto indicazioni precise su ogni attività da sospendere.",
          "points": 2
        },
        {
          "key": "C",
          "text": "Verifico le nuove priorità, valuto cosa mettere in pausa e riorganizzo il lavoro.",
          "points": 4
        },
        {
          "key": "D",
          "text": "Interrompo immediatamente tutto ciò che stavo facendo e passo alla nuova attività.",
          "points": 2
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Adattabilità",
        "secondary": "Orientamento al risultato"
      }
    },
    {
      "id": 36,
      "text": "Un cliente o un collega ti segnala un problema, ma le informazioni che ti fornisce sono incomplete.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Trasferisco subito la questione a qualcuno che conosce meglio l'argomento.",
          "points": 2
        },
        {
          "key": "B",
          "text": "Faccio alcune domande mirate per ricostruire il problema prima di decidere come intervenire.",
          "points": 4
        },
        {
          "key": "C",
          "text": "Propongo subito la soluzione che considero più probabile.",
          "points": 2
        },
        {
          "key": "D",
          "text": "Gli chiedo di ricontattarmi quando avrà tutte le informazioni.",
          "points": 1
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": null
      }
    },
    {
      "id": 37,
      "text": "Ricevi un feedback negativo su un lavoro che ritenevi ben fatto.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Ascolto il feedback, faccio domande per comprenderlo e valuto quali elementi utilizzare per migliorare.",
          "points": 4
        },
        {
          "key": "B",
          "text": "Accetto il feedback senza discuterlo, anche se non sono d'accordo.",
          "points": 2
        },
        {
          "key": "C",
          "text": "Preferisco confrontarmi con altri colleghi per capire se il feedback sia effettivamente corretto.",
          "points": 3
        },
        {
          "key": "D",
          "text": "Spiego subito le ragioni delle mie scelte.",
          "points": 1
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": "Adattabilità"
      }
    },
    {
      "id": 38,
      "text": "Un collega ti chiede aiuto mentre stai lavorando a un'attività importante.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Gli suggerisco di chiedere direttamente al responsabile.",
          "points": 2
        },
        {
          "key": "B",
          "text": "Interrompo immediatamente ciò che sto facendo per aiutarlo.",
          "points": 2
        },
        {
          "key": "C",
          "text": "Gli dico che non posso aiutarlo perché devo concentrarmi sulla mia attività.",
          "points": 1
        },
        {
          "key": "D",
          "text": "Cerco di capire urgenza e necessità della richiesta e concordo quando e come posso supportarlo senza compromettere le priorità.",
          "points": 4
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Collaborazione e comunicazione",
        "secondary": "Orientamento al risultato"
      }
    },
    {
      "id": 39,
      "text": "Ti accorgi che una procedura utilizzata abitualmente potrebbe essere resa più semplice ed efficace.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Continuo a utilizzare la procedura esistente perché è quella prevista.",
          "points": 1
        },
        {
          "key": "B",
          "text": "Raccolgo qualche elemento a supporto della mia idea e propongo il miglioramento alle persone coinvolte.",
          "points": 4
        },
        {
          "key": "C",
          "text": "Ne parlo informalmente con i colleghi, ma aspetto che sia qualcun altro a proporre il cambiamento.",
          "points": 2
        },
        {
          "key": "D",
          "text": "Modifico direttamente il processo e inizio a utilizzare il nuovo metodo.",
          "points": 3
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Autonomia e iniziativa",
        "secondary": null
      }
    },
    {
      "id": 40,
      "text": "Devi prendere una decisione, ma non disponi di tutte le informazioni che vorresti.",
      "type": "scenario",
      "answers": [
        {
          "key": "A",
          "text": "Rimando la decisione finché non dispongo di tutte le informazioni.",
          "points": 1
        },
        {
          "key": "B",
          "text": "Chiedo a una persona più esperta di decidere al mio posto.",
          "points": 2
        },
        {
          "key": "C",
          "text": "Identifico quali informazioni sono davvero indispensabili, raccolgo quelle disponibili e prendo una decisione valutando anche i possibili rischi.",
          "points": 4
        },
        {
          "key": "D",
          "text": "Scelgo rapidamente sulla base della mia prima impressione.",
          "points": 2
        }
      ],
      "scoring": {
        "inverse": false,
        "primary": "Problem solving e analisi",
        "secondary": "Adattabilità"
      }
    }
  ],
  "competencies": [
    {
      "name": "Accountability e affidabilità",
      "suggestion": "Chiedere un esempio di errore o ritardo e verificare comunicazione, responsabilità e azioni correttive."
    },
    {
      "name": "Problem solving e analisi",
      "suggestion": "Proporre un problema concreto e osservare come raccoglie informazioni, formula ipotesi e valuta alternative."
    },
    {
      "name": "Collaborazione e comunicazione",
      "suggestion": "Approfondire un disaccordo con un collega e verificare ascolto, assertività e gestione del confronto."
    },
    {
      "name": "Adattabilità",
      "suggestion": "Chiedere un esempio di cambio di priorità, strumento o processo e come ha riorganizzato il lavoro."
    },
    {
      "name": "Orientamento al risultato",
      "suggestion": "Approfondire una situazione con più priorità e verificare criteri di scelta, perseveranza e attenzione all’impatto."
    },
    {
      "name": "Autonomia e iniziativa",
      "suggestion": "Chiedere un caso in cui ha dovuto partire con indicazioni incomplete e come ha bilanciato autonomia e richiesta di supporto."
    }
  ],
  "ranges": [
    {
      "min": 80,
      "max": 100,
      "label": "Tendenza molto marcata",
      "interview": "Verificare punti di forza con evidenze concrete"
    },
    {
      "min": 65,
      "max": 79.99,
      "label": "Tendenza abbastanza marcata",
      "interview": "Verificare punti di forza con evidenze concrete"
    },
    {
      "min": 45,
      "max": 64.99,
      "label": "Area intermedia",
      "interview": "Verificare coerenza con esempi comportamentali"
    },
    {
      "min": 0,
      "max": 44.99,
      "label": "Tendenza poco rappresentata",
      "interview": "Approfondire con esempi concreti; non interpretare come esclusione"
    }
  ],
  "weights": {
    "primary": 1.0,
    "secondary": 1.0
  }
}$vvseed$::jsonb,true,now());
    insert into public.audit_logs(event) values('Applicazione inizializzata — versione 1.0 importata dall’Excel');
  end if;
end
$bootstrap$;

-- Dopo aver creato manualmente l'utente HR in Authentication > Users,
-- esegui UNA VOLTA questa query sostituendo l'email:
-- insert into public.hr_users(user_id)
-- select id from auth.users where lower(email)=lower('hr@voipvoice.it')
-- on conflict(user_id) do nothing;
